### ISSUE TITLE
github.com/dgrijalva/jwt-go

### ISSUE THREAD

**Issue by bbrodriges** [gofrs/help-requests#41]
Where is the project currently hosted?

> https://github.com/dgrijalva/jwt-go
> 

What languages other than Go does the project utilize?

> none
> 

When was the project's last activity?

> Jan 7, 2020
> 

Does the project have a maintainer, or a maintainer looking for someone to take over the project?

> The current maintainer is not active anymore. See https://github.com/dgrijalva/jwt-go/issues/457
> 

What active projects replicate the popular functionality of this project, if any?

> github.com/lestrrat-go/jwx - incompatible with jwt-go.
> gopkg.in/square/go-jose.v2 - incompatible, restrictive disclaimer about encryption.
> 

What are some example projects that make use of this package?

> github.com/gin-gonic/contrib/jwt
> github.com/go-kit/kit/auth/jwt
> github.com/go-echo/echo/middleware
>

Are there any outstanding **_critical_** bugs that result in the library being totally unusable or insecure?

> Critical CVE vulnerability - https://github.com/dgrijalva/jwt-go/issues/428
> 

Please provide a link to the project importers from https://godoc.org.

> https://pkg.go.dev/github.com/dgrijalva/jwt-go?tab=importedby
> 

What else would you like to mention about the project?

> Most popular JWT Go library so far
>

**Comment by cristaloleg** [comment]
That's one of the reasons why I've made another JWT library, targeting on a simplicity and performance. Feel free to check it https://github.com/cristalhq/jwt 

Also multiple `aud` in `RegisteredClaims` is pretty popular.

**Comment by mfridman** [comment]
There was another discussion over at https://github.com/dgrijalva/jwt-go/issues/462

Like the others that commented, I believe `dgrijalva/jwt-go` should live as an independently maintained project (instead of a personal account or one affiliated with a company) with at least a few maintainers, [some offered to help](https://github.com/dgrijalva/jwt-go/issues/462#issuecomment-828170032)

I believe the short-term goal is to:

1. patch any outstanding security issues
2. add module support
3. maintain the existing `jwt-go` API in its current form
4. drop travis in favour of github actions, assuming `gofrs` org allows it

The intention is to support the package in its current form without any major re-write or refactor. 

---

As mentioned by OP, other libraries and forks for jwt already exist. Hopefully one day we'll see a jwt package added to the Go standard library, but until then migrating maintenance of `dgrijalva/jwt-go` to the `gofrs` org is the best option imo.

What are the next steps?

**Comment by bbrodriges** [comment]
It seems like https://github.com/golang-jwt/jwt is the new location of original repo. @dgrijalva added appropriate section to the README.
