### ISSUE TITLE
Slack alternatives 

### ISSUE THREAD

**Issue by fbaube** [gofrs/help-requests#6]
Is there a way to discuss opportunities without using Slack ?

**Comment by theckman** [comment]
@fbaube at this time if you can't use Slack, your secondary option would likely be a GitHub issue. Because the Go community has converged on Slack, nearing 30k users, it made the most sense to build around that.

**Comment by fbaube** [comment]
I'd be happy with a list of projects that have passed "review", plus a PoC (for all or per-project) for chipping in. But I see now there's quite a list of projects collected in this issues list :)

**Comment by theckman** [comment]
@fbaube I'm going to work on getting a simple website up with this information, and more, ideally within the next week.

**Comment by jadr2ddude** [comment]
We could set up a gitter, but I do not know how helpful that would really be. Having a second stream of chat would complicate things.

**Comment by pedromorgan** [comment]
Simple decision for me./..

Gitter integrates with gh+gl..

Slack is proprietry and not invited..

**Comment by pedromorgan** [comment]
And stuff Slack. .lets for IRC..

**Comment by theckman** [comment]
I definitely don't want to insulate anyone from our effort by choosing a specific chat medium, but I think if you look within the context of the larger Go community there's been a coalescing of people towards Slack. Whether or not you like Slack, it's hard to argue with 30.5k registered users. It's also open for anyone to join, by requesting an invite [here](https://invite.slack.golangbridge.org/).

We're fortunate to have a public Slack workspace with unlimited chat history, which other communities don't have. I can tell you as an admin of the Slack workspace itself, it's not a great platform for an open community for a few reasons. So with that said, I'll admit that I am not always a huge fan of it for our use case.

However, I'm pushing my personal opinions aside and am considering the community as a whole. In doing so I look around, and it seems to be the most common/frequented space we have. If you disagree / have data showing otherwise I'm genuinely interested in pursuing looking in to that. However, that's a strong signal in deciding to use it as "home base" for now.

On top of that, more and more companies are moving to Slack each day, and so I assume more people are using their platform each day. With people already being in the tool for work, and to frequent the Go community, it's easy for them to engage with us. Once we increase the barrier to entry, I see that changing drastically. 

That said, this is only my personal opinion on this. I am interested in the perspectives of others, although I think with most of us being in Slack already there may be an implicit bias.

**Comment by theckman** [comment]
@gofrs/all thoughts?

**Comment by zerkms** [comment]
In cases when I have multiple choices and want to make a kind-of-scientific decision I create a table where I enumerate the constraints I have/goals I want to achieve, those choices, and their corresponding pros/cons weighted against constraints/goals.

If the slack (as an place where the initiative group met each other originally) does not work well, I propose to create at least a list with the goals and constraints, so that we did have a formal list of things that need to be achieved to become "more welcome to diverse set of developers".

Otherwise this whole thread would become not-so-productive and based of preferences and biases.

**Comment by Xe** [comment]
Slack works well enough for now IMO. It's not worth dying on that hill.

**Comment by theckman** [comment]
Happy to revisit later if someone wants to raise a new issue. For now I'd say we're committed to Slack.
