### ISSUE TITLE
gads - Google Adwords API for Go

### ISSUE THREAD

**Issue by GithubUser5462** [gofrs/help-requests#9]
* Where is the project currently hosted?
Multiple forks based on https://github.com/emiddleton/gads

* Is the project written only in Go, or does it contain other languages (beyond scripts)?
Only in Go

* Has the project had any recent activity?
Some forks tried to implement a newer version of the api with unclear success.

* Does the project have a maintainer, or a maintainer looking for someone to take
  over the project?
No active maintainer, last commit was on 8 Sep 2015

* Do you have any example projects that make use of this package?
It's used as a library.

* Are there any outstanding **_critical_** bugs that result in the library being
  totally unusable or insecure?
Google updates the api every couple of months or so. The original project is completely unusable, some of the forks have tried to implement the latest version of the api but most of them are incoplete.

* Is there anything else you'd like to mention about the project?

**Comment by theckman** [comment]
Here are the AdWords API docs:

- https://developers.google.com/adwords/api/docs/guides/start

They definitely don't make it an appealing API to have to work with, especially in Go:

>The AdWords API relies on SOAP and WSDL technologies to offer its services.

@GithubUser5462 would you be able to provide any estimates for how much work you'd think would be involved in upgrading this package to work with the newer versions of the API?

>- Do you have any example projects that make use of this package?
>It's used as a library.

Would you be able to provide an example of any open source packages that make use of this, or can you identify any users of this package? I ask because we're hoping to focus our efforts on projects that have the most impact for the Go ecosystem, and to do that we need to understand what the usage of this project is like. The only projects I could identify appear to be itself or forks:

- https://godoc.org/github.com/emiddleton/gads?importers

**Comment by theckman** [comment]
It doesn't seem like this project is a good fit for us right now, so I'm going to close this issue. Thank you for taking the time to giving us the opportunity to see if this project would be a good fit.
